language: node_js
node_js: stable

install:
  - npm install

before_script:
  - hexo clean
  - hexo g

script:
  - cd ./public
  - git init
  - git config --global user.name "FrankJiang92"
  - git config --global user.email "jiangfan92@foxmail.com"
  - git add .
  - git commit -m 'update docs by travis ci'
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

branches:
  only:
    - src

env:
 global:
   - GH_REF: github.com/FrankJiang92/FrankJiang92.github.io.git